services:
  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    container_name: users
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - "mongo"
    volumes:
      - ./users:/app/users
      - /app/users/node_modules

  proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - users
    ports:
      - 80:80

  mongo:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
    container_name: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
