services:
  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    container_name: users
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - "mongo"
    volumes:
      - ./users:/app/users
      - /app/users/node_modules

  places:
    build:
      dockerfile: Dockerfile
      context: ./places
    container_name: places
    ports:
      - "3002:3002"
    restart: always
    depends_on:
      - "postgres"
    volumes:
      - ./places:/app/places
      - /app/places/node_modules

  proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - users
      - places
    ports:
      - 80:80

  mongo:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
    container_name: mongo
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  mongo-data:
  postgres-data:
